# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-08 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_tab',
            field=models.BooleanField(default=False, verbose_name='是否放在导航'),
        ),
    ]
